name: Auto Merge PRs to Dev

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Enable Auto Merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: merge
